version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install python3-pip
      - pip install --upgrade pip
      - python3.8 --version
      - pip3 install virtualenv
      - virtualenv venv
      - . venv/bin/activate
  build:
    commands:
      - pip3 install -r requirements.txt
  post_build:
    commands:
      - python3 main.py
      - echo Build completed!