version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install python3-pip
      - apt-get install python3.8
      - python3.8 --version
  build:
    commands:
      - echo Building..
  post_build:
    commands:
      - echo Build completed!